apiVersion: v1
kind: ConfigMap
metadata:
  name: temperature-app-config
data:
  APPLICATION_NAME: "temperature-microservice"
  SERVER_PORT: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-microservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperature-microservice
  template:
    metadata:
      labels:
        app: temperature-microservice
    spec:
      containers:
      - name: temperature-microservice
        image: temperature-microservice:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: temperature-app-config
        volumeMounts:
          - name: readings-volume
            mountPath: /app/data/readings.csv # Ovo je proizvoljno, tj. definiramo gdje se unutar kontejnera nalazi file
            subPath: readings.csv
            readOnly: true
      volumes:
        - name: readings-volume
          configMap:
            name: readings
            

---
apiVersion: v1
kind: Service
metadata:
  name: temperature-microservice
spec:
  selector:
    app: temperature-microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
